### PR TITLE
Contact section html code with css code

### LINKED ISSUE #5: contact section
details of how clients can reach us or send an inquiry

### PR DESCRIPTION
**Pull request by micaela-21**
fixes #5 email of our website is included as well as the form suggested by @jeanne-strg our social media are also linked

### CODE REVIEW

**Comment by DonnTv** [comment]
Putting icons to link our socials is mindful for easy access

**Comment by camille-vrx** [comment]
Its also good that making the color of icons still related to our website.

**Comment by micaela-21** [comment]
Should i merge it now?

**Comment by jeanne-strg** [comment]
Yes, you can. No problem.

**Pull request merged**
